version: '3.8'

services:
  app:
    image: node:16
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "npm install && npm run dev"
